export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const RESET_REGISTER_SUCCESS='RESET_REGISTER_SUCCESS';

export const SET_AUTH_LOADING='SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING='REMOVE_AUTH_LOADING';

